name: 'Install PHP'
description: 'Github Composite action to install php'
inputs:
  version:
    description: 'version of PHP you will like to install'
    required: true
    default: '8.1'
runs:
  using: "composite"
  steps:
  - name: Get php version
     run: |
       echo "CURRENT_PHP_VERSION=$(sh php --version)" >> $GITHUB_ENV
       shell: bash
       
    - name: Install php
      if: "! contains(env.CURRENT_PHP_VERSION, php${{ inputs.version}})"
      run: |
        sudo apt-get update -y
        sudo apt-get install -y php${{ inputs.version}}
      shell: bash
