name: 'Install PHP'
description: 'Github Composite action to install php'
inputs:
  version:
    description: 'version of PHP you will like to install'
    required: true
    default: '8.1'
runs:
  using: "composite"
  steps:
    - name: Install python
      if: "! contains(toJSON(steps), 'python3')"
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.10.0
      shell: bash
